### ISSUE TITLE
google authentication

### ISSUE THREAD

**Issue by Wingless-Archangel** [nccgroup/autochrome#10]
I tried to login with google authentication (oauth) in this case I tested with gmail.com but I couldn't authenticate. it shows unknown error.
![gmail](https://user-images.githubusercontent.com/3817329/41756374-3decc336-7617-11e8-9339-bc554b159381.png)

Step to reproduce
1. open the custom build chromium
2. try to login normally (my account has multi-factor authentication enabled)
3. got the error.

**Comment by peter-h-ncc** [comment]
Closing, please re-open the issue if it is still a problem.
