### ISSUE TITLE
Work-around for recent versions of Chromium

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/autochrome#15]
AutoChrome isn't compatible with recent versions of Chromium. However, it is possible to force the download of a specific version with the "-V" switch.

So let's use an old and compatible one: $ ruby ./autochrome.rb -V 612442 -c

That will install the fully compatible version 72.0.3626.0

**Comment by 3isenHeiM** [comment]
I've just installed in on the latest Chromium version (1009982) without problem.

The only issue I have is a warning message : "You are using an supported command-line flag: --ignore-certificate-errors.`

But other than that it works just fine.

**Comment by peter-h-ncc** [comment]
I cannot replicate this, please re-open this issue with comment if the problem still exists.
