### ISSUE TITLE
Warning "You are using an unsupported command-line flag"

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/autochrome#27]
Hello,

when launching AutoChrome, the message "You are using an unsupported command-line flag" appears. That can be fixed by adding the following line to the `chrome` script:

     "--test-type",

Source: https://groups.google.com/a/chromium.org/forum/#!msg/chromium-discuss/O4WpwWvGz4A/jmrypvjNEQAJ
Reference: https://peter.sh/experiments/chromium-command-line-switches/

**Comment by peter-h-ncc** [comment]
I cannot replicate this, if it is still a problem please re-open this issue.
